allowBuilds:
  '@parcel/watcher': true
  core-js: true
  esbuild: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - vuetify@4.1.3
onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - esbuild
  - unrs-resolver
