import type MetaInterface from '@/interfaces/MetaInterface';

// This file is auto-generated by the build system.
const meta: MetaInterface = {
  version: '0.1.0',
  date: '2022-03-06T02:43:22.279Z',
};
export default meta;
