import MetaInterface from '@/interfaces/MetaInterface';

// This file is auto-generated by the build system.
const meta: MetaInterface = {
  version: '0.0.0',
  date: '2022-02-12T00:54:51.001Z',
};
export default meta;
