import MetaInterface from '@/interfaces/MetaInterface';

// This file is auto-generated by the build system.
const meta: MetaInterface = {
  version: '0.0.2',
  date: '2022-02-18T05:55:17.328Z',
};
export default meta;
